### ISSUE TITLE
Front-End Engineer Avançado

### ISSUE THREAD

**Issue by ghost** [concretesolutions/front-end-guide#1]
Fala @matheusml,  tentando contribuir um pouco eu considero que um Engenheiro Avançado teria como básico entender também:

- Dominar o ambiente do navegador (Render, Painting e etc).
- Entender sobre o protocolo Http e o que o cerca ( Segurança, three-way handshake do TCP, como funciona uma requisição).
- Além de conseguir criar uma app usando 100% js acredito que saber deployar também.

Criei essa issue caso alguém queira discutir e se considera algo a mais como essencial poder contribuir.

**Comment by matheusml** [comment]
Legal @edmolima 

São bons pontos de fato, você consegue criar um PR com essas mudanças?

**Comment by ghost** [comment]
Claro agora mesmo @matheusml vou abrir fechando essa issue =)
